### ISSUE TITLE
Deliver milestone 2

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Antelope-SSI-Toolkit#23]
Definition of done

- [x]    Fork this repository with the same GitHub account that you used to submit the application.
 - [x]  In the newly created fork, create a copy of the milestone delivery template (deliveries/milestone-delivery-template.md). 
 - [x]  Fill out the template with the details of your milestone, including all deliverables as listed in your application.
    Name the file project_name-milestone_number.md.
 - [ ]   Fill out the invoice form.
 - [ ]  Create a pull request and fill out the comment template.
-  [ ] Discuss with product owner on followup tasks like Marketing and Reporting to the board. 
- [ ] Finance update 

https://github.com/eosnetworkfoundation/grant-milestones#milestone-delivery-process

**Comment by theblockstalk** [comment]
https://github.com/eosnetworkfoundation/grant-milestones/pull/50
